### ISSUE TITLE
Correct example import on npmjs.com

### ISSUE THREAD

**Issue by probert100** [alhazmy13/angular-csv-ext#29]
This is a small issue..

Currently  example on https://www.npmjs.com/package/angular5-csv has `import { Angular5Csv } from 'angular5-csv/Angular5-csv';`
but github page and what actually works is  `import { Angular5Csv } from 'angular5-csv/dist/Angular5-csv';`

**Comment by rob-moore** [comment]
This is a good catch I assumed that the readme would be pulled automatically into the npm description. I think that's something that @alhazmy13 has to update. Thanks for catching this though!

**Comment by paaatcha** [comment]
> This is a small issue..
> 
> Currently example on https://www.npmjs.com/package/angular5-csv has `import { Angular5Csv } from 'angular5-csv/Angular5-csv';`
> but github page and what actually works is `import { Angular5Csv } from 'angular5-csv/dist/Angular5-csv';`

I was trying to import the lib and got the same problem.
Good job @probert100!

**Comment by gbeford** [comment]
This just bit me as well, Might want to update your website https://www.code-sample.com/2018/05/export-to-excel-csv-angular-5-6.html and on the NPM site https://www.npmjs.com/package/angular5-csv both show the wrong import.

**Comment by argodeep** [comment]
Thanks. import { Angular5Csv } from 'angular5-csv/dist/Angular5-csv'; still working on angular 8.

**Comment by alhazmy13** [comment]
Hi all, We fixed this in version [1.0.0](https://github.com/alhazmy13/angular-csv-ext/releases/tag/1.0.0)

Please note: The new name for this package is `angular-csv-ext`, so remove `angular5-csv` and install the new one.

Thanks
