### ISSUE TITLE
When module failed it causes app down

### ISSUE THREAD

**Issue by ricLuo** [alhazmy13/angular-csv-ext#31]
Hi I'm a user of this csv module and really appreciate you developed this angular5-csv module. It helps a lot.
Yesterday I'm experiencing error with this module. It said cannot find this module. It causes my company's website down in production. So I'm asking is there a way to prevent this from happening ? Or could I do any configuration of webpack for the failure tolerance ?
Thanks

**Comment by asfo** [comment]
You need to change the import, they used without the dist, now you need to add it in the import like 

`import { Angular5Csv } from 'angular5-csv/dist/Angular5-csv';`

**Comment by ricLuo** [comment]
> You need to change the import, they used without the dist, now you need to add it in the import like
> 
> `import { Angular5Csv } from 'angular5-csv/dist/Angular5-csv';`

Hi asfo,

Thanks for your reply. I actually solve it by wrap it in try catch block and using "require" to import module. I found that it possibly happens because the Azure cloud which we deployed our app, moved our app to new server so all the packages get reinstalled and application restarted. I also changed the path to "dist" as you recommended

Also thanks for your reply

**Comment by asfo** [comment]
Don't worry, nice to read that you solve your issue. I just add my comment in case someone else needs to fix this because I had this issue again and I remember that I read some people were having the same issue.

**Comment by alhazmy13** [comment]
Hi all, We fixed this in version [1.0.0](https://github.com/alhazmy13/angular-csv-ext/releases/tag/1.0.0)

Please note: The new name for this package is `angular-csv-ext`, so remove `angular5-csv` and install the new one.

Thanks

**Comment by ricLuo** [comment]
> Hi all, We fixed this in version [1.0.0](https://github.com/alhazmy13/angular-csv-ext/releases/tag/1.0.0)
> 
> Please note: The new name for this package is `angular-csv-ext`, so remove `angular5-csv` and install the new one.
> 
> Thanks


Thanks
