### ISSUE TITLE
npm 1.0.0

### ISSUE THREAD

**Issue by kthomas182** [alhazmy13/angular-csv-ext#34]
Can you publish 1.0.0 to npm so we can get past this npm warning?

npm WARN angular5-csv@0.2.11 requires a peer of @angular/core@^5.0.0 but none is installed. You must install peer dependencies yourself.

**Comment by rajatrocks37** [comment]
@alhazmy13 Any update on this issue ?
I need to update my dependency. Can you please publish the same.

**Comment by alhazmy13** [comment]
Hi all, We fixed this in version [1.0.0](https://github.com/alhazmy13/angular-csv-ext/releases/tag/1.0.0)

Please note: The new name for this package is `angular-csv-ext`, so remove `angular5-csv` and install the new one.

Thanks
