### ISSUE TITLE
Please remove Wrong import statement in npmjs

### ISSUE THREAD

**Issue by vadempur** [alhazmy13/angular-csv-ext#36]
In npmjs import statement is wrong please replace with correct import statement

**Comment by h3xx** [comment]
Evidently this broke when updating 0.2.10 -> 0.2.11.

Really, though, devs: a patch level bump should not break all existing import statements.

**Comment by argodeep** [comment]
Use this for import { Angular5Csv } from 'angular5-csv/dist/Angular5-csv';

**Comment by h3xx** [comment]
Possible dupe of #29

**Comment by alhazmy13** [comment]
Hi all, We fixed this in version [1.0.0](https://github.com/alhazmy13/angular-csv-ext/releases/tag/1.0.0)

Please note: The new name for this package is `angular-csv-ext`, so remove `angular5-csv` and install the new one.

Thanks
