### ISSUE TITLE
Angular 8 support

### ISSUE THREAD

**Issue by madhav5589** [alhazmy13/angular-csv-ext#38]
I am using angular5-csv version 0.2.11 and while trying to upgrade to Angular 8, it throws below error:

`Package "angular5-csv" has an incompatible peer dependency to "@angular/core" (requires "^5.0.0" (extended), would install "8.0.0").`

Also, seems like angularcsv-5 has dependency on rxjs 5.x.  ON upgrade page, Angular team has suggested to migrate to rxjs 6.x for angular 8.

`Package "angular5-csv" has an incompatible peer dependency to "rxjs" (requires "^5.5.2", would install "6.5.2").`

Thanks.

**Comment by mrvini** [comment]
any updates on this issue? that is blocking angular update

**Comment by bnadem** [comment]
i have the same problem

**Comment by suryacyg** [comment]
This is required ASAP

**Comment by alhazmy13** [comment]
Hi all, We fixed this in version [1.0.0](https://github.com/alhazmy13/angular-csv-ext/releases/tag/1.0.0)

Please note: The new name for this package is `angular-csv-ext`, so remove `angular5-csv` and install the new one.

Thanks
