### ISSUE TITLE
Angular 8 support

### ISSUE THREAD

**Issue by eyassud** [alhazmy13/angular-csv-ext#41]
I upgrading to Angular 8 and I get the following error

Package "angular5-csv" has an incompatible peer dependency to "rxjs" (requires "^5.5.2", would install "6.5.2").

Do you support Angular 8?

**Comment by madhav5589** [comment]
This is duplicate of #38 and is already fixed. Please upgrade the library to latest version. Also make sure that the name of repo has been updated in the latest version.
